CREATE TABLE partition0
PARTITION OF partitioned
FOR VALUES WITH (MODULUS 10, REMAINDER 0);

CREATE TABLE partition1
PARTITION OF partitioned
FOR VALUES WITH (MODULUS 10, REMAINDER 1);

CREATE TABLE partition2
PARTITION OF partitioned
FOR VALUES WITH (MODULUS 10, REMAINDER 2);

CREATE TABLE partition3
PARTITION OF partitioned
FOR VALUES WITH (MODULUS 10, REMAINDER 3);

CREATE TABLE partition4
PARTITION OF partitioned
FOR VALUES WITH (MODULUS 10, REMAINDER 4);

CREATE TABLE partition5
PARTITION OF partitioned
FOR VALUES WITH (MODULUS 10, REMAINDER 5);

CREATE TABLE partition6
PARTITION OF partitioned
FOR VALUES WITH (MODULUS 10, REMAINDER 6);

CREATE TABLE partition7
PARTITION OF partitioned
FOR VALUES WITH (MODULUS 10, REMAINDER 7);

CREATE TABLE partition8
PARTITION OF partitioned
FOR VALUES WITH (MODULUS 10, REMAINDER 8);

CREATE TABLE partition9
PARTITION OF partitioned
FOR VALUES WITH (MODULUS 10, REMAINDER 9)
